In [1]:
FEATURES = ["dom_x", "dom_y", "dom_z", "dom_time", "charge"]  # (x,y,z,t,q)

In [2]:
from typing import Dict, Callable
import torch

In [3]:
import sys, os

# go two levels up:  .../Graphnet-Applications
repo_root = os.path.abspath("..")
sys.path.append(repo_root)
from MyClasses.detector_pone import PONE

graphnet [MainProcess] WARNING  2026-01-08 13:18:02 - has_jammy_flows_package - `jammy_flows` not available. Normalizing Flow functionality is missing.


In [4]:
det = PONE(
    replace_with_identity=["charge", "dom_time", "dom_x", "dom_y", "dom_z"]
)

graphnet [MainProcess] INFO     2026-01-08 13:18:02 - PONE.__init__ - Writing log to logs/graphnet_20260108-131802.log


In [5]:
from graphnet.data.dataset.parquet.parquet_dataset import ParquetDataset
from graphnet.models.detector.prometheus  import  Prometheus
from graphnet.models.graphs  import  KNNGraph
from graphnet.models.graphs.nodes  import  NodesAsPulses

FEATURES = ["dom_x", "dom_y", "dom_z", "dom_time", "charge"]  # (x,y,z,t,q)

data_representation = KNNGraph(
    detector=PONE(),
    node_definition=NodesAsPulses(),
    nb_nearest_neighbours=8,
    distance_as_edge_feature = True
)

dataset = ParquetDataset(
    path="/project/def-nahee/kbas/POM_Response_Parquet/merged" ,
    pulsemaps="features",
    truth_table="truth",
    features=FEATURES,
    truth=["energy"],
    data_representation = data_representation,
)



graphnet [MainProcess] WARNING  2026-01-08 13:18:08 - has_icecube_package - `icecube` not available. Some functionality may be missing.
graphnet [MainProcess] WARNING  2026-01-08 13:18:09 - has_km3net_package - `km3net` not available. Some functionality may be missing.
graphnet [MainProcess] WARNING  2026-01-08 13:18:09 - <module> - `graphnet.models.graphs` will be depricated soon. All functionality has been moved to `graphnet.models.data_representation`.


In [6]:
dir(dataset)

['__abstractmethods__',
 '__add__',
 '__annotations__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__orig_bases__',
 '__parameters__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_cache_size',
 '_calculate_sizes',
 '_check_missing_columns',
 '_chunk_cumsum',
 '_chunk_sizes',
 '_config',
 '_configure_root_logger',
 '_construct_dataset_from_list_of_strings',
 '_construct_datasets_from_dict',
 '_create_graph',
 '_data_representation',
 '_dtype',
 '_features',
 '_file_cache',
 '_get_all_indices',
 '_get_dbang_label',
 '_get_event_index',
 '_get_formatters',
 '_get_labels',
 '_get_root_logger',
 '_get_row_idx',
 '_graph_definition',

In [7]:
len(dataset)

746

In [8]:
graph = dataset[696] 
graph

Data(x=[4570, 5], n_pulses=4570, dataset_path='/project/def-nahee/kbas/POM_Response_Parquet/merged', event_no=[1], muon=-1, muon_stopped=-1, noise=-1, neutrino=-1, v_e=-1, v_u=-1, v_t=-1, track=-1, dbang=-1, corsika=-1, energy=[1], graph_definition='KNNGraph', data_representation='KNNGraph', edge_index=[2, 43480], num_nodes=4570, edge_attr=[43480, 1], features=[5], dom_x=[4570], dom_y=[4570], dom_z=[4570], dom_time=[4570], charge=[4570])

In [9]:
dir(graph)

['__abstractmethods__',
 '__annotations__',
 '__call__',
 '__cat_dim__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__inc__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_edge_attr_cls',
 '_edge_to_layout',
 '_edges_to_layout',
 '_find_parent',
 '_get_edge_index',
 '_get_tensor',
 '_get_tensor_size',
 '_multi_get_tensor',
 '_put_edge_index',
 '_put_tensor',
 '_remove_edge_index',
 '_remove_tensor',
 '_store',
 '_tensor_attr_cls',
 '_to_type',
 '_union',
 'apply',
 'apply_',
 'batch',
 'clone',
 'coalesce',
 'c

In [10]:
graph.keys()          

['muon_stopped',
 'x',
 'v_t',
 'track',
 'dom_x',
 'dom_z',
 'event_no',
 'dataset_path',
 'data_representation',
 'features',
 'v_u',
 'muon',
 'dom_time',
 'energy',
 'edge_attr',
 'neutrino',
 'graph_definition',
 'num_nodes',
 'n_pulses',
 'edge_index',
 'corsika',
 'dom_y',
 'dbang',
 'charge',
 'v_e',
 'noise']

In [11]:
graph.energy          # truth burada

tensor([639.4667], dtype=torch.float64)

In [12]:
graph.dom_x

tensor([-120., -120., -120.,  ...,  240.,  240.,  240.])

In [13]:
graph.event_no

tensor([696.], dtype=torch.float64)

In [14]:
graph.track

tensor(-1)

In [15]:
graph.num_nodes

4570

In [16]:
graph.graph_definition

'KNNGraph'

In [17]:
graph.x

tensor([[-1.2000e+02, -7.3072e+02, -3.0000e+02,  1.8648e+03,  1.4324e+00],
        [-1.2000e+02, -7.3072e+02, -1.5000e+02,  3.7829e+03,  1.2572e+00],
        [-1.2000e+02, -7.3072e+02, -1.5000e+02,  9.1115e+03,  1.1472e+00],
        ...,
        [ 2.4000e+02,  7.2420e+02,  2.0000e+02,  4.9448e+03,  9.6772e-01],
        [ 2.4000e+02,  7.2420e+02,  4.0000e+02,  3.3093e+02,  5.9688e-01],
        [ 2.4000e+02,  7.2420e+02,  4.0000e+02,  8.8986e+03,  9.3520e-01]])

In [18]:
graph.x.shape

torch.Size([4570, 5])

In [19]:
graph.v_t

tensor(-1)

In [20]:
graph.v_u

tensor(-1)

In [21]:
graph.data_representation

'KNNGraph'

In [22]:
graph.charge

tensor([1.4324, 1.2572, 1.1472,  ..., 0.9677, 0.5969, 0.9352])

In [23]:
graph.dataset_path

'/project/def-nahee/kbas/POM_Response_Parquet/merged'

In [24]:
graph.muon

tensor(-1)

In [25]:
graph.features

['dom_x', 'dom_y', 'dom_z', 'dom_time', 'charge']

In [26]:
graph.corsika

tensor(-1)

In [27]:
graph.neutrino

tensor(-1)

In [28]:
graph.n_pulses

tensor(4570, dtype=torch.int32)

In [29]:
graph.noise

tensor(-1)

In [30]:
graph.dom_z

tensor([-300., -150., -150.,  ...,  200.,  400.,  400.])

In [31]:
graph.dom_y

tensor([-730.7180, -730.7180, -730.7180,  ...,  724.2047,  724.2047,
         724.2047])

In [32]:
graph.dbang

tensor(-1)

In [33]:
graph.muon_stopped

tensor(-1)

In [34]:
graph.v_e

tensor(-1)

In [35]:
graph.dom_time

tensor([1864.7611, 3782.9058, 9111.4590,  ..., 4944.7783,  330.9313,
        8898.5986])

In [36]:
graph.edge_index

tensor([[   0,    0,    0,  ..., 4569, 4569, 4569],
        [  12,   13,   14,  ..., 4557, 4558, 4568]])

In [37]:
graph.edge_index.shape

torch.Size([2, 43480])

In [38]:
graph.edge_attr

tensor([[128.0625],
        [128.0625],
        [ 80.0000],
        ...,
        [ 80.0000],
        [ 94.3398],
        [  0.0000]])

In [39]:
graph.edge_attr.shape

torch.Size([43480, 1])

In [40]:
graph.node_attrs

<bound method BaseData.node_attrs of Data(x=[4570, 5], n_pulses=4570, dataset_path='/project/def-nahee/kbas/POM_Response_Parquet/merged', event_no=[1], muon=-1, muon_stopped=-1, noise=-1, neutrino=-1, v_e=-1, v_u=-1, v_t=-1, track=-1, dbang=-1, corsika=-1, energy=[1], graph_definition='KNNGraph', data_representation='KNNGraph', edge_index=[2, 43480], num_nodes=4570, edge_attr=[43480, 1], features=[5], dom_x=[4570], dom_y=[4570], dom_z=[4570], dom_time=[4570], charge=[4570])>

In [41]:
graph.num_edge_features

1

In [42]:
graph.num_edges

43480

In [43]:
from graphnet.data.dataloader import DataLoader


In [44]:
help(DataLoader)

Help on class DataLoader in module graphnet.data.dataloader:

class DataLoader(torch.utils.data.dataloader.DataLoader)
 |  DataLoader(dataset: graphnet.data.dataset.dataset.Dataset, batch_size: int = 1, shuffle: bool = False, num_workers: int = 1, persistent_workers: bool = True, collate_fn: Callable = <function collate_fn at 0x15178674a200>, prefetch_factor: int = 2, **kwargs: Any) -> None
 |  
 |  Class for loading data from a `Dataset`.
 |  
 |  Method resolution order:
 |      DataLoader
 |      torch.utils.data.dataloader.DataLoader
 |      typing.Generic
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, dataset: graphnet.data.dataset.dataset.Dataset, batch_size: int = 1, shuffle: bool = False, num_workers: int = 1, persistent_workers: bool = True, collate_fn: Callable = <function collate_fn at 0x15178674a200>, prefetch_factor: int = 2, **kwargs: Any) -> None
 |      Construct `DataLoader`.
 |  
 |  -----------------------------------------------------

In [45]:
loader = DataLoader(
    dataset,
    batch_size=128,
    shuffle=True,
    num_workers=10,
    multiprocessing_context="spawn",  
    persistent_workers=True,         
)


# datasetleri onceden ayirip ayri ayri koysan iyi olcak gibi. merged icine train, test, val koy

/project/6061446/kbas/pone_offline/graphnet_env/lib/python3.10/site-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 10 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


In [46]:
it = iter(loader)


graphnet [SpawnProcess-1] WARNING  2026-01-08 13:18:55 - has_icecube_package - `icecube` not available. Some functionality may be missing.
graphnet [SpawnProcess-1] WARNING  2026-01-08 13:18:56 - has_km3net_package - `km3net` not available. Some functionality may be missing.
graphnet [SpawnProcess-1] WARNING  2026-01-08 13:18:59 - has_jammy_flows_package - `jammy_flows` not available. Normalizing Flow functionality is missing.
graphnet [SpawnProcess-2] WARNING  2026-01-08 13:19:01 - has_icecube_package - `icecube` not available. Some functionality may be missing.
graphnet [SpawnProcess-2] WARNING  2026-01-08 13:19:02 - has_km3net_package - `km3net` not available. Some functionality may be missing.
graphnet [SpawnProcess-2] WARNING  2026-01-08 13:19:05 - has_jammy_flows_package - `jammy_flows` not available. Normalizing Flow functionality is missing.
graphnet [SpawnProcess-3] WARNING  2026-01-08 13:19:07 - has_icecube_package - `icecube` not available. Some functionality may be missing.

In [47]:
batch = next(it)


In [48]:
batch

DataBatch(x=[586999, 5], n_pulses=[128], dataset_path=[128], event_no=[128], muon=[128], muon_stopped=[128], noise=[128], neutrino=[128], v_e=[128], v_u=[128], v_t=[128], track=[128], dbang=[128], corsika=[128], energy=[128], graph_definition=[128], data_representation=[128], edge_index=[2, 5639572], num_nodes=586999, edge_attr=[5639572, 1], features=[128], dom_x=[586999], dom_y=[586999], dom_z=[586999], dom_time=[586999], charge=[586999], batch=[586999], ptr=[129])

In [49]:
batch.batch

tensor([  0,   0,   0,  ..., 127, 127, 127])

In [50]:
batch.edge_index

tensor([[     0,      0,      0,  ..., 586998, 586998, 586998],
        [     1,      2,     13,  ..., 586878, 586894, 586985]])

In [51]:
batch.edge_index.shape

torch.Size([2, 5639572])

In [52]:
batch.x

tensor([[-1.2000e+02, -7.3072e+02, -4.0000e+02,  6.4477e+03,  8.9255e-01],
        [-1.2000e+02, -7.3072e+02, -3.5000e+02,  4.7636e+02,  1.3393e+00],
        [-1.2000e+02, -7.3072e+02, -3.0000e+02,  9.3320e+03,  9.7971e-01],
        ...,
        [ 2.4000e+02,  7.2420e+02,  1.5000e+02,  2.6812e+03,  8.3198e-01],
        [ 2.4000e+02,  7.2420e+02,  3.0000e+02,  8.3377e+01,  9.8733e-01],
        [ 2.4000e+02,  7.2420e+02,  5.0000e+02,  3.3136e+03,  9.4542e-01]])

In [53]:
# spawn ney ogren. burda spawn process

In [54]:
from graphnet.models.components.layers import DynEdgeConv

In [55]:
import torch.nn as nn
mlp = nn.Sequential(
    nn.Linear(10, 32),    ### 10 is 2*5
    nn.ReLU(),
    nn.Linear(32, 256)   
)

In [56]:
layer = DynEdgeConv(
    nn=mlp,
    nb_neighbors=8,  
    features_subset=None,
    aggr = "add"
)

In [57]:
x1, edge_index1 = layer(batch.x, batch.edge_index, batch=batch.batch)

In [58]:
batch.x.shape

torch.Size([586999, 5])

In [59]:
x1.shape

torch.Size([586999, 256])

In [60]:
batch.edge_index.shape
# bu ok degil

torch.Size([2, 5639572])

In [61]:
edge_index1.shape
# bu ok 

torch.Size([2, 4695992])

## neden :(

Koduna baktığımda her şey genel olarak mantıklı görünüyor. Yani KNNGraph ile baştan itibaren nb_nearest_neighbours=8 olarak belirlemişsin ve bu ayarlar da DynEdgeConv layer’ına düzgünce yansıtılmış. Buna rağmen edge sayısında fazlalık devam ediyorsa, bu durumda veri setinin ilk oluşturulduğu aşamada eklenmiş ekstra kenarlar olabileceğini düşünüyorum.

Yani aslında kodun mantığı doğru ama KNNGraph oluşturulurken veri setinin bir şekilde zaten fazladan edge ile gelmiş olması mümkün. Belki de distance_as_edge_feature=True parametresi ya da NodesAsPulses tanımı sırasında beklenmedik ekstra komşuluklar oluşmuş olabilir.

Bu durumda yapılabilecek şeylerden biri, batch.edge_index’i layer’dan önce bir kez kontrol edip, fazladan kenarları elle temizlemeyi denemek olabilir. Ya da KNNGraph tanımında veya PONE içindeki ayarlarda fazladan bir şeyin eklenmediğinden emin olmak için ayarları gözden geçirebilirsin.

Kısacası, kodun doğru yolda, sadece veri setinin baştan fazla edge ile gelmesi olasılığını bir kontrol etmek faydalı olur.