In [17]:
import numpy as np
PMT_ANGLES = np.array( [[57.5, 270.],  # PMT 1
                        [57.5, 0.],    # PMT 2
                        [57.5, 90.],   # PMT 3
                        [57.5, 180.],  # PMT 4
                        [25., 225.],   # PMT 5
                        [25., 315.],   # PMT 6
                        [25., 45.],    # PMT 7
                        [25., 135.],   # PMT 8
                        [-57.5, 270.], # PMT 9
                        [-57.5, 180.], # PMT 10
                        [-57.5, 90.],  # PMT 11
                        [-57.5, 0.],   # PMT 12
                        [-25., 315.],  # PMT 13
                        [-25., 225.],  # PMT 14
                        [-25., 135.],  # PMT 15
                        [-25., 45.]    # PMT 16
                        ])

In [18]:
MODULE_RADIUS_M      = 0.2159

In [19]:
x_coordinates = np.multiply(np.sin(np.deg2rad(90. - PMT_ANGLES[:, 0])), np.cos(np.deg2rad(PMT_ANGLES[:, 1])))
y_coordinates = np.multiply(np.sin(np.deg2rad(90. - PMT_ANGLES[:, 0])), np.sin(np.deg2rad(PMT_ANGLES[:, 1])))
z_coordinates = np.cos(np.deg2rad(90. - PMT_ANGLES[:, 0]))


In [20]:
PMT_MATRIX = np.array([x_coordinates, y_coordinates, z_coordinates]).T

In [21]:
PMT_COORDINATES = PMT_MATRIX * MODULE_RADIUS_M
PMT_COORDINATES

array([[-2.13094027e-17, -1.16002985e-01,  1.82088213e-01],
       [ 1.16002985e-01,  0.00000000e+00,  1.82088213e-01],
       [ 7.10313424e-18,  1.16002985e-01,  1.82088213e-01],
       [-1.16002985e-01,  1.42062685e-17,  1.82088213e-01],
       [-1.38360893e-01, -1.38360893e-01,  9.12432827e-02],
       [ 1.38360893e-01, -1.38360893e-01,  9.12432827e-02],
       [ 1.38360893e-01,  1.38360893e-01,  9.12432827e-02],
       [-1.38360893e-01,  1.38360893e-01,  9.12432827e-02],
       [-2.13094027e-17, -1.16002985e-01, -1.82088213e-01],
       [-1.16002985e-01,  1.42062685e-17, -1.82088213e-01],
       [ 7.10313424e-18,  1.16002985e-01, -1.82088213e-01],
       [ 1.16002985e-01,  0.00000000e+00, -1.82088213e-01],
       [ 1.38360893e-01, -1.38360893e-01, -9.12432827e-02],
       [-1.38360893e-01, -1.38360893e-01, -9.12432827e-02],
       [-1.38360893e-01,  1.38360893e-01, -9.12432827e-02],
       [ 1.38360893e-01,  1.38360893e-01, -9.12432827e-02]])

In [25]:
print(type(PMT_COORDINATES))

<class 'numpy.ndarray'>


In [26]:
def Rx(deg):
    th = np.deg2rad(deg)
    c, s = np.cos(th), np.sin(th)
    return np.array([[1,0,0],[0,c,-s],[0,s,c]], dtype=float)

In [27]:
R = Rx(-90)
R

array([[ 1.000000e+00,  0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  6.123234e-17,  1.000000e+00],
       [ 0.000000e+00, -1.000000e+00,  6.123234e-17]])

In [28]:
PMT_COORDINATES_ORIGINAL = PMT_COORDINATES @ R.T

In [29]:
PMT_COORDINATES_ORIGINAL

array([[-2.13094027e-17,  1.82088213e-01,  1.16002985e-01],
       [ 1.16002985e-01,  1.82088213e-01,  1.11496874e-17],
       [ 7.10313424e-18,  1.82088213e-01, -1.16002985e-01],
       [-1.16002985e-01,  1.82088213e-01, -3.05658111e-18],
       [-1.38360893e-01,  9.12432827e-02,  1.38360893e-01],
       [ 1.38360893e-01,  9.12432827e-02,  1.38360893e-01],
       [ 1.38360893e-01,  9.12432827e-02, -1.38360893e-01],
       [-1.38360893e-01,  9.12432827e-02, -1.38360893e-01],
       [-2.13094027e-17, -1.82088213e-01,  1.16002985e-01],
       [-1.16002985e-01, -1.82088213e-01, -2.53559559e-17],
       [ 7.10313424e-18, -1.82088213e-01, -1.16002985e-01],
       [ 1.16002985e-01, -1.82088213e-01, -1.11496874e-17],
       [ 1.38360893e-01, -9.12432827e-02,  1.38360893e-01],
       [-1.38360893e-01, -9.12432827e-02,  1.38360893e-01],
       [-1.38360893e-01, -9.12432827e-02, -1.38360893e-01],
       [ 1.38360893e-01, -9.12432827e-02, -1.38360893e-01]])

In [11]:
from typing import TYPE_CHECKING, Any, Dict, List, Optional
from graphnet.data.extractors.icecube.utilities.frames import (get_om_keys_and_pulseseries)
from graphnet.utilities.imports import has_icecube_package

if has_icecube_package() or TYPE_CHECKING:
    from icecube import icetray, dataclasses, dataio  # pyright: reportMissingImports=false

from graphnet.data.extractors.icecube import (
    I3FeatureExtractorIceCube86
)
import numpy as np



class I3FeatureExtractorPONE(I3FeatureExtractorIceCube86):
    """Class for extracting reconstructed features for P-ONE events created with LeptonInjector."""
    
    def __init__(
        self,
        pulsemap: str,
        name: str = "feature", 
        exclude: list = [None],
    ):
       
        # Base class constructor
        super().__init__(pulsemap=pulsemap, exclude=exclude)
        self._extractor_name = name

        self._detector_status: Optional["icetray.I3Frame.DetectorStatus"] = None 
        self._PMT_ANGLES = np.array( [[57.5, 270.],  # PMT 1
                        [57.5, 0.],    # PMT 2
                        [57.5, 90.],   # PMT 3
                        [57.5, 180.],  # PMT 4
                        [25., 225.],   # PMT 5
                        [25., 315.],   # PMT 6
                        [25., 45.],    # PMT 7
                        [25., 135.],   # PMT 8
                        [-57.5, 270.], # PMT 9
                        [-57.5, 180.], # PMT 10
                        [-57.5, 90.],  # PMT 11
                        [-57.5, 0.],   # PMT 12
                        [-25., 315.],  # PMT 13
                        [-25., 225.],  # PMT 14
                        [-25., 135.],  # PMT 15
                        [-25., 45.]    # PMT 16
                        ])
        self.MODULE_RADIUS_M = 0.2159
        
        self._pmt_x_coordinates_wrt_om_rotated = np.multiply(np.sin(np.deg2rad(90. - self._PMT_ANGLES[:, 0])), np.cos(np.deg2rad(self._PMT_ANGLES[:, 1])))
        self._pmt_y_coordinates_wrt_om_rotated = np.multiply(np.sin(np.deg2rad(90. - self._PMT_ANGLES[:, 0])), np.sin(np.deg2rad(self._PMT_ANGLES[:, 1])))
        self._pmt_z_coordinates_wrt_om_rotated = np.cos(np.deg2rad(90. - self._PMT_ANGLES[:, 0]))
        
        self._PMT_MATRIX_rotated = np.array([self._pmt_x_coordinates_wrt_om_rotated,  self._pmt_y_coordinates_wrt_om_rotated, self._pmt_z_coordinates_wrt_om_rotated]).T
  
        self._PMT_COORDINATES_rotated = self._PMT_MATRIX_rotated * self.MODULE_RADIUS_M


        self._minus_90_degree_rotation_around_x_axis =  np.array([
            [1.000000e+00, 0.000000e+00, 0.000000e+00],
            [0.000000e+00, 0.000000e+00, 1.000000e+00],
            [0.000000e+00, -1.000000e+00, 0.000000e+00]], dtype=float)
    
    
        self._PMT_COORDINATES_ORIGINAL = self._PMT_COORDINATES_rotated @ self._minus_90_degree_rotation_around_x_axis.T
        
        ### kontrol et kankiiiii dogru mu burdaki islemler. görsel ile tekrar incele. 
        ### he bi de su silindiri rotate etme mevzusunu da bi incele
        ### pmt numaralari da karisiyor muuu ona da bak kankitom
        ### bi de init et ve kontrol et pmt konumlari dogru update edilmis mi OM'den
        

        
    def set_gcd(self, i3_file: str, gcd_file: Optional[str] = None) -> None:
        """Extract GFrame, CFrame and DFrame from i3/gcd-file pair.

           Information from these frames will be set as member variables of
           `I3Extractor.`

        Args:
            i3_file: Path to i3 file that is being converted.
            gcd_file: Path to GCD file. Defaults to None. If no GCD file is
                      given, the method will attempt to find C and G frames in
                      the i3 file instead. If either one of those are not
                      present, `RuntimeErrors` will be raised.
        """
        super().set_gcd(i3_file=i3_file, gcd_file=gcd_file)
        
        if gcd_file is None:
            # If no GCD file is provided, search the I3 file for frames
            # containing geometry (GFrame) and calibration (CFrame)
            gcd = dataio.I3File(i3_file)
        else:
            # Ideally ends here
            gcd = dataio.I3File(gcd_file)
        
        try:
            d_frame = gcd.pop_frame(icetray.I3Frame.DetectorStatus)
        except RuntimeError as e:
            self.error(
                "No GCD file was provided "
                f"and no D-frame was found in {i3_file.split('/')[-1]}."
            )
            raise e
            
        self._detector_status = d_frame



    def __call__(self, frame: "icetray.I3Frame") -> Dict[str, List[Any]]:
        """Extract reconstructed features from `frame`.

        Args:
            frame: Physics (P) I3-frame from which to extract reconstructed
                features.

        Returns:
            Dictionary of reconstructed features for all pulses in `pulsemap`,
                in pure-python format.
        """
        padding_value: float = -1.0
        output: Dict[str, List[Any]] = {
            "charge": [],
            "dom_time": [],
            "width": [],
            "dom_x": [],
            "dom_y": [],
            "dom_z": [],
            "pmt_area": [],
            "rde": [],
            "is_bright_dom": [],
            "is_bad_dom": [],
            "is_saturated_dom": [],
            "is_errata_dom": [],
            "event_time": [],
            "hlc": [],
            "awtd": [],
            "string": [],
            "pmt_number": [],
            "dom_number": [],
            "dom_type": [],
            "pmt_x": [],
            "pmt_y": [],
            "pmt_z": []
        }
        # Get OM data
        if self._pulsemap in frame:
            om_keys, data = get_om_keys_and_pulseseries(
                frame,
                self._pulsemap,
                self._calibration,
            )
        else:
            self.warning_once(f"Pulsemap {self._pulsemap} not found in frame.")
            return output

        # Added these :
        is_bright_dom = -1
        is_saturated_dom = -1
        is_errata_dom = -1
        
        bad_doms = None
        
        if "BadDomsList" in self._detector_status:
            bad_doms = self._detector_status["BadDomsList"]


        event_time = frame["I3EventHeader"].start_time.mod_julian_day_double  ## what is this

        for om_key in om_keys:
            # Common values for each OM
            x = self._gcd_dict[om_key].position.x
            y = self._gcd_dict[om_key].position.y
            z = self._gcd_dict[om_key].position.z
            area = self._gcd_dict[om_key].area
            rde = self._get_relative_dom_efficiency(
                frame, om_key, padding_value
            )

            string = om_key[0]
            dom_number = om_key[1]
            pmt_number = om_key[2]
            dom_type = self._gcd_dict[om_key].omtype
            
            pmt_x = pmt_y = pmt_z = padding_value
            
            if pmt_number is not None:
                idx = int(pmt_number) - 1
                if 0 <= idx < len(self._PMT_COORDINATES_ORIGINAL):
                    rel = self._PMT_COORDINATES_ORIGINAL[idx]  # rel = [dx, dy, dz]
                    pmt_x = x + float(rel[0])
                    pmt_y = y + float(rel[1])
                    pmt_z = z + float(rel[2])


            # DOM flags

            if bad_doms:
                is_bad_dom = 1 if om_key in bad_doms else 0
            else:
                is_bad_dom = int(padding_value)


            # Loop over pulses for each OM
            pulses = data[om_key]
            for pulse in pulses:
                output["charge"].append(
                    getattr(pulse, "charge", padding_value)
                )
                output["dom_time"].append(
                    getattr(pulse, "time", padding_value)
                )
                output["width"].append(getattr(pulse, "width", padding_value))
                output["pmt_area"].append(area)
                output["rde"].append(rde)
                output["dom_x"].append(x)
                output["dom_y"].append(y)
                output["dom_z"].append(z)
                output["pmt_x"].append(pmt_x)
                output["pmt_y"].append(pmt_y)
                output["pmt_z"].append(pmt_z)
                # ID's
                output["string"].append(string)
                output["pmt_number"].append(pmt_number)
                output["dom_number"].append(dom_number)
                output["dom_type"].append(dom_type)
                # DOM flags
                output["is_bad_dom"].append(is_bad_dom)
                output["event_time"].append(event_time)
                output["is_bright_dom"].append(is_bright_dom)
                output["is_errata_dom"].append(is_errata_dom)
                output["is_saturated_dom"].append(is_saturated_dom)

                # Pulse flags
                flags = getattr(pulse, "flags", padding_value)
                if flags == padding_value:
                    output["hlc"].append(padding_value)
                    output["awtd"].append(padding_value)
                else:
                    output["hlc"].append((pulse.flags >> 0) & 0x1)  # bit 0
                    output["awtd"].append(self._parse_awtd_flag(pulse))

        return output
    



 # icecube86'den editlemem gereken method var mi bak. buradaki yaptiklarim duzenli mi ona da bak. temizle bi her seyi. 
 # time seylerini anla
  

In [10]:
DATA_PATH = "/project/def-nahee/kbas/POM_Response_GZ/pom_response_batch_100.i3.gz"
GCD_PATH = "/project/6008051/pone_simulation/GCD_Library/PONE_800mGrid.i3.gz"

In [13]:
feature_extractor = I3FeatureExtractorPONE(pulsemap="EventPulseSeries")

feature_extractor.set_gcd(gcd_file=GCD_PATH, i3_file=DATA_PATH)

In [14]:
data_file = dataio.I3File(DATA_PATH)
data_file.pop_frame()
frame = data_file.pop_frame()

In [15]:
import pandas as pd
pd.DataFrame(feature_extractor(frame))

charge     dom_time  width  dom_x       dom_y  dom_z  pmt_area  rde  \
0     0.908205  9359.085568    NaN -120.0 -730.717968 -250.0  0.585754  1.0   
1     0.607176  8596.747512    NaN -120.0 -730.717968 -250.0  0.585754  1.0   
2     0.589521  9032.962231    NaN -120.0 -730.717968 -250.0  0.585754  1.0   
3     1.016980    60.014573    NaN -120.0 -730.717968 -200.0  0.585754  1.0   
4     1.241295  5623.710408    NaN -120.0 -730.717968 -150.0  0.585754  1.0   
...        ...          ...    ...    ...         ...    ...       ...  ...   
4468  0.538176  8636.502857    NaN  240.0  724.204711   50.0  0.585754  1.0   
4469  0.748448  5105.651210    NaN  240.0  724.204711  250.0  0.585754  1.0   
4470  0.810974  3771.891846    NaN  240.0  724.204711  300.0  0.585754  1.0   
4471  0.414474  2140.963185    NaN  240.0  724.204711  450.0  0.585754  1.0   
4472  0.793512  2139.488463    NaN  240.0  724.204711  450.0  0.585754  1.0   

      is_bright_dom  is_bad_dom  ...  event_time  hlc   awtd  string  \
0                -1          -1  ...   -678943.0    0  False       1   
1                -1          -1  ...   -678943.0    0  False       1   
2                -1          -1  ...   -678943.0    0  False       1   
3                -1          -1  ...   -678943.0    0  False       1   
4                -1          -1  ...   -678943.0    0  False       1   
...             ...         ...  ...         ...  ...    ...     ...   
4468             -1          -1  ...   -678943.0    0  False     340   
4469             -1          -1  ...   -678943.0    0  False     340   
4470             -1          -1  ...   -678943.0    0  False     340   
4471             -1          -1  ...   -678943.0    0  False     340   
4472             -1          -1  ...   -678943.0    0  False     340   

      pmt_number  dom_number  dom_type       pmt_x       pmt_y       pmt_z  
0              3           5       130 -120.000000 -730.535879 -250.116003  
1             14           5       130 -120.138361 -730.809211 -249.861639  
2             15           5       130 -120.138361 -730.809211 -250.138361  
3              6           6       130 -119.861639 -730.626724 -199.861639  
4              3           7       130 -120.000000 -730.535879 -150.116003  
...          ...         ...       ...         ...         ...         ...  
4468           7          11       130  240.138361  724.295954   49.861639  
4469           9          15       130  240.000000  724.022622  250.116003  
4470          14          16       130  239.861639  724.113467  300.138361  
4471           2          19       130  240.116003  724.386799  450.000000  
4472           7          19       130  240.138361  724.295954  449.861639  

[4473 rows x 22 columns]

In [ ]:
## did not affect much :D expected consdiering the distance between OMs being 80 (?) m

In [30]:
PMT_COORDINATES_ORIGINAL

array([[-2.13094027e-17,  1.82088213e-01,  1.16002985e-01],
       [ 1.16002985e-01,  1.82088213e-01,  1.11496874e-17],
       [ 7.10313424e-18,  1.82088213e-01, -1.16002985e-01],
       [-1.16002985e-01,  1.82088213e-01, -3.05658111e-18],
       [-1.38360893e-01,  9.12432827e-02,  1.38360893e-01],
       [ 1.38360893e-01,  9.12432827e-02,  1.38360893e-01],
       [ 1.38360893e-01,  9.12432827e-02, -1.38360893e-01],
       [-1.38360893e-01,  9.12432827e-02, -1.38360893e-01],
       [-2.13094027e-17, -1.82088213e-01,  1.16002985e-01],
       [-1.16002985e-01, -1.82088213e-01, -2.53559559e-17],
       [ 7.10313424e-18, -1.82088213e-01, -1.16002985e-01],
       [ 1.16002985e-01, -1.82088213e-01, -1.11496874e-17],
       [ 1.38360893e-01, -9.12432827e-02,  1.38360893e-01],
       [-1.38360893e-01, -9.12432827e-02,  1.38360893e-01],
       [-1.38360893e-01, -9.12432827e-02, -1.38360893e-01],
       [ 1.38360893e-01, -9.12432827e-02, -1.38360893e-01]])